## Indexação de Numpys e Array
Selecionando elementos ou grupos de elementos de uma matriz.

In [2]:
import numpy as np

In [13]:
# Criando um simples array
arr = np.arange(0,12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Indexação e seleção
A maneira mais simples de escolher um ou alguns elementos de uma matriz é muito semelhante às listas de python:

In [12]:
# Obtendo um valor através de um índice, semelhante a uma lista
arr[8]

8

In [14]:
# Obtendo valores em um intervalo
arr[1:5] # intervalo de posição [1 até 5)

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

## Transmissão

Numpy arrays diferem de uma lista Python normal por causa de sua capacidade de transmissão:

In [6]:
# Configurando um valor com intervalo de índice (Transmissão)
arr[0:5]=100 # multipla transmissão de dados

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11])

In [3]:
# Redefinir matriz, veremos por que eu tive que redefinir em um momento
arr = np.arange(0,11)

# Mostrando
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Notas importantes sobre uma fatia de um array (ou subarray)
slice_de_arr = arr[0:6]

# Mostra a fatia
slice_de_arr

array([0, 1, 2, 3, 4, 5])

In [8]:
# Modificando a fatia
slice_de_arr[:]=99

#Show Slice again
slice_de_arr

99

Agora note que as mudanças também ocorrem em nossa matriz original!

In [9]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Os dados não são copiados, é uma visão da matriz original! Isso evita problemas de memória!

In [10]:
# Para obter uma cópia, precisa ser explícito
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexando uma matriz 2D

Notações **array[row][col]** ou **array[row, col]**

In [14]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

# Mostrando
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [15]:
# Fila de indexação
arr_2d[1]


array([20, 25, 30])

In [16]:
# Obtendo o valor do elemento individual
arr_2d[1][0]

20

In [17]:
# alternativa de obtendo o valor do elemento individual
arr_2d[1,0]

20

In [18]:
# Fatiando um array 2D

# Fatia (2,2) do canto superior direito
arr_2d[:2,1:] # linhas [do começo até 2) colunas [1 até o final] 

array([[10, 15],
       [25, 30]])

In [19]:
# Fatia inferior
arr_2d[2]
#alternativamente
arr_2d[2,:]

array([35, 40, 45])

### Indexação "Fancy"

A indexação "Fancy" permite que você selecione linhas inteiras ou colunas fora da ordem:

In [3]:
## consiremos a matriz abaixo
arr2d = np.zeros((10,10))

In [4]:
# Tamaho do array
arr_length = arr2d.shape[1]


In [7]:
for i in range(arr_length):
    for j in range (arr_length):
        arr2d[i,j] = i+j/10
    
arr2d

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9],
       [2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9],
       [4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9],
       [5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9],
       [6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9],
       [7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9],
       [8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9],
       [9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9]])

Indexação "Fancy" permite o seguinte:

In [8]:
arr2d[[2,4,6,8]] # extraindo linhas pares

array([[2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9],
       [4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9],
       [6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9],
       [8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9]])

Restrigindo linha e coluna

In [9]:
arr2d[[2,4,6,8],2:6] # extraindo linhas pares com colunas da posição 2 ate a posição 6

array([[2.2, 2.3, 2.4, 2.5],
       [4.2, 4.3, 4.4, 4.5],
       [6.2, 6.3, 6.4, 6.5],
       [8.2, 8.3, 8.4, 8.5]])

In [34]:
# Permite em qualquer ordem também
arr2d[[6,4,2,7],4:9]

array([[6.4, 6.5, 6.6, 6.7, 6.8],
       [4.4, 4.5, 4.6, 4.7, 4.8],
       [2.4, 2.5, 2.6, 2.7, 2.8],
       [7.4, 7.5, 7.6, 7.7, 7.8]])

## Seleção ou filtro
Operadores para comparação

In [26]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [28]:
bool_arr = arr>4

In [29]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [30]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [31]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])