# NumPy 

NumPy (ou Numpy) é um pacote(ou biblioteca) de álgebra linear para Python veloz devido a ligações com bibliotecas C. É um pacote fundamental, pois quase todas as bibliotecas de ciências de dados do Python tem rotinas internas que dependem do NumPy.

Glossário das principais funções, guas e o manual completo pode ser visto site oficial do Numpy: https://numpy.org/


### Chamando o NumPy

In [1]:
import numpy as np # import a biblioteca NumPy e no qual será abreviado por 'np' 

Numpy possui muitas funções e nós vamos conhecer: vetores, arrays, matrizes e geração de números. 

## Numpy Arrays

Numpy arrays tem dois formatos mais comuns: vetores, de uma dimensão e as matrizes com duas dimensões. 
Seu principal objeto é o ``ndarray``.

Vamos começar nossa introdução explorando como criar matrizes numPy.


## Criando Arrays

### De uma lista de Python

Podemos criar uma matriz convertendo diretamente a partir de uma lista (lista de listas):

In [2]:
minha_lista = [1,2,3]
print(minha_lista)
type(minha_lista)

[1, 2, 3]


list

In [3]:
minha_array=np.array(minha_lista)
print(minha_array)
type(minha_array)

[1 2 3]


numpy.ndarray

### Fazendo diretamente

In [8]:
arr_numpy = np.array([5,30,40,50])
print(arr_numpy)

[ 5 30 40 50]


### Criando matrizes

In [6]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]
print(minha_matriz)
type(minha_matriz)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


list

In [8]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Podemos também criar uma matriz a partir de um array

In [22]:
matriz = np.array([1,2,3,4])
matriz.shape = (2,2) # alterando a dimensão
print(matriz)

[[1 2]
 [3 4]]


### Métodos importantes


### arange

Retorna valores inteiros em um determinado intervalo.

In [3]:
np.arange(0,10) # note que seria o intervalo [0,9) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,11,2) # de 0 a 10 de 2 em 2

array([ 0,  2,  4,  6,  8, 10])

### Repeat e tile

*repeat* repete listas ou vetores por elemento 


*tile* repete toda lista ou vetor


In [13]:
y=[10,20]
print(np.repeat(y, [2, 3]))

m_seq=np.repeat(y, [2, 3])
np.tile(m_seq,2)


[10 10 20 20 20]


array([10, 10, 20, 20, 20, 10, 10, 20, 20, 20])

### zeros e ones

Gerar matrizes de zeros ou de ums

In [7]:
np.zeros(3) # uma dimensão

array([0., 0., 0.])

In [8]:
np.zeros((5,5)) # matriz quadrada 5x5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Retorna 'n' números uniformemente espaçados em um intervalo.

In [12]:
np.linspace(0,10,3) # retorna 3 números entre 0 e 10 

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,10,50) # agora 50 números entre 0 e 10

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Cria uma matriz identidade

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy também tem implementado maneiras de criar arrays de números aleatórios obtidos por meio de distribuições de probabilidade. 

### rand
Cria um array e preencha com amostras aleatórias da distribuição uniforme entre ``[0, 1)``.

In [20]:
np.random.rand(2)

array([ 0.46634816,  0.13377055])

In [21]:
np.random.rand(5,5)

array([[ 0.17673782,  0.89778905,  0.63435534,  0.71063947,  0.77599807],
       [ 0.43508517,  0.91318032,  0.26845102,  0.47684911,  0.99352832],
       [ 0.46549283,  0.61358868,  0.83033769,  0.96269353,  0.40539354],
       [ 0.42690345,  0.62643046,  0.63229206,  0.70472064,  0.56361411],
       [ 0.64975573,  0.99581894,  0.22271032,  0.98653378,  0.81032733]])

### randn

Retorna uma amostra (ou amostras) da distribuição normal padronizada, com Média=0 e variância=1. 

In [19]:
np.random.randn(2)

array([-0.55622818, -0.91990835])

In [16]:
np.random.randn(5,5)

array([[-0.94763074, -1.86234993, -0.62030439,  1.66173946,  0.53114936],
       [ 1.605552  , -0.87519428, -0.57951714,  1.12265208,  0.2437291 ],
       [-1.10001741,  0.67523098,  0.55207007, -0.44393244,  1.16931881],
       [ 1.00607023, -0.06121843,  0.8734925 ,  0.82336132,  0.54921895],
       [ 0.11405619,  0.34174379,  0.01062177,  0.63842651,  0.81691097]])

### randint
Retorna inteiros aleatórios de um intervalo do tipo ``(a,b]`` 

In [24]:
np.random.randint(1,100)

98

In [25]:
np.random.randint(1,100,10)

array([18, 22, 55,  2, 94, 17, 98, 98, 73, 91])

### Atributos de Array e Métodos

Atributos e métodos úteis:

In [23]:
arr = np.arange(25)

ranarr = np.random.randint(0,50,10)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr

array([30, 32,  0, 31, 33,  4, 40, 28, 27, 43])

## Reshape
Retorna uma matriz contendo os mesmos dados com uma nova forma.

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Shape

Shape é um atributo (característica) dos arrays indicando sua dimensão. 

OBS: Não é um método (ou função aplicável) que no Python ficam entre parenteses. 

In [44]:
# Mostrando a dimensão de um Vector
print(arr)
arr.shape 


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


(25,)

In [39]:
t_arr=arr.reshape(1,25) # alterando a dimensão para 1x25 (uma linha e 25 colunas)
t_arr.shape

(1, 25)

In [40]:
print(t_arr) # note que temos agora colchetes duplos inciando e fechando. O que indica uma matriz 

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]]


In [45]:
arr.reshape(25,1) # alterando arr para uma matriz 25x1

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])