# Operações em NumPy

## Operações artiméticas

Operações elemento a elemento. 

In [3]:
import numpy as np
arr = np.arange(0,10)

In [3]:
arr + arr # vale o mesmo para subtração multiplicação e divisão

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr**3 # potenciação

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Funções aplicadas em elementos

Numpy vem com muitas [funções de matrizes](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), que são essenciais nas apenas operações matemáticas por elemento da matriz. Exemplos:

In [8]:
# Tomando raízes quadradas
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [9]:
# Calculando exponenciais (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

## Operações algebricas mais comuns usando a biblioteca linealg do NumPy 
[ver mais detalhes neste link](https://numpy.org/doc/stable/reference/routines.linalg.html)

### Matrizes

In [4]:
A=np.array(([2,8,6],[4,5,7],[6,4,4]))
B=np.array(([1,9,5],[3,9,4],[5,3,3]))
C=np.array(([1,2],[2,1],[1,2]))
print(A)
print(B)
C

[[2 8 6]
 [4 5 7]
 [6 4 4]]
[[1 9 5]
 [3 9 4]
 [5 3 3]]


array([[1, 2],
       [2, 1],
       [1, 2]])

### Multiplicação

In [37]:
## Elemento por elemento
A*B # Precisam ter mesma dimensão (vale para soma + , diferença - e divisão / )



array([[ 2, 72, 30],
       [12, 45, 28],
       [30, 12, 12]])

In [5]:
## Multiplicação de matrizes 

## O número de colunas da primeira matriz tem que ser igual ao número de linha da segunda matriz
## Resultando muma matriz com número de linhas da primeira e numero de colunas da segunda matriz
### 3X3 multiplicada por 3x2 é valido e gera uma matriz 3x2

A@B
B@C # Note que não seria válido C@B 

array([[24, 21],
       [25, 23],
       [14, 19]])

### Transposta, Diagonal e Traço de uma matriz (Soma da diagonal principal)

In [40]:
print(np.diag(A)) # diagonal
print(np.trace(A)) # traço
np.transpose(C) # trasposta

[2 5 4]
11


array([[1, 2, 1],
       [2, 1, 2]])

### Inversa de uma Matriz

In [44]:
np.linalg.pinv(A)

array([[-0.07407407, -0.07407407,  0.24074074],
       [ 0.24074074, -0.25925926,  0.09259259],
       [-0.12962963,  0.37037037, -0.2037037 ]])

### Determinante de uma Matriz

In [48]:
np.linalg.det(A)

108.00000000000003

### Autovalores e Autovetores

In [49]:
autovalores, autovetores = np.linalg.eig(A) 
print(autovalores)
print(autovetores)

[15.26348856+0.j         -2.13174428+1.59102958j -2.13174428-1.59102958j]
[[ 0.60064678+0.j          0.46333329-0.36675488j  0.46333329+0.36675488j]
 [ 0.59688441+0.j          0.34004711+0.28156429j  0.34004711-0.28156429j]
 [ 0.53193274+0.j         -0.67520562+0.j         -0.67520562-0.j        ]]


In [50]:
np.linalg.linalg.det(A)

108.00000000000003